---
# install docker on ubuntu clients with default apt setup
- hosts: '{{ ANSIBLE_HOSTS }}'
  vars_files:
    - group_vars/all.yml
  become: true
  tasks:

  ## https://docs.docker.com/engine/install/ubuntu/
  
    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install a list of packages and set up the repository
      ansible.builtin.apt:
        pkg:
          - ca-certificates 
          - curl 
          - gnupg

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
