---
# install docker on ubuntu clients with default apt setup
- hosts: '{{ ANSIBLE_HOSTS }}'
  vars_files:
    - group_vars/all.yml
  become: true
  tasks:

  ## https://docs.docker.com/engine/install/ubuntu/

    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install a list of packages and set up the repository
      ansible.builtin.apt:
        pkg:
          - ca-certificates 
          - curl 
          - gnupg

    - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          keyring: /etc/apt/keyrings/docker.gpg
          state: present
    
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
          repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
          state: present
          filename: docker

    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install a docker-ce packages
      ansible.builtin.apt:
        pkg:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin


