---
# wget https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
# zabbix-release_latest+ubuntu22.04_all.deb 
# dpkg -i zabbix-release_6.4-1+ubuntu22.04_all.deb
# apt update 
- hosts: 
  vars_files:
    - group_vars/all.yml
  become: true
  tasks:


#### Install Repos

    - name: Install a Zabbix-Latest.deb package from the internet
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb

    - name: Update apt
      ansible.builtin.apt:
        update_cache: yes

    - name: Install a zabbix-agent2 packages
      ansible.builtin.apt:
        pkg:
          - zabbix-agent2
          - zabbix-agent2-plugin-*

    - name: Stop service zabbix-agent2.service, if running
      ansible.builtin.systemd:
          name: zabbix-agent2.service
          state: stopped

    - name: create psk file in opt
      template:
          backup: true
          src: group_vars/zabbix_agentd.j2
          dest: /opt/zabbix_agentd.psk
          owner: zabbix
          group: zabbix
          mode: 0644

    - name: Update zabbix config safely with backup
      ansible.builtin.template:
        src: group_vars/zabbix_agent2.conf.j2
        dest: /etc/zabbix/zabbix_agent2.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Start service zabbix-agent2.service, if running
      ansible.builtin.systemd:
          name: zabbix-agent2.service
          state: started
